org.gradle.caching = true
org.gradle.configuration-cache=false
org.gradle.jvmargs = -Xms512M -Xmx2048M
org.gradle.parallel = true
#android.useAndroidX = true
#android.uniquePackageNames = false
kotlin.code.style = official
version = 1.1.0
description = Plugin to assist with patch tests and creation for ReVanced
